### ISSUE TITLE
Milestone 03 Review

### ISSUE THREAD

**Issue by EddieYao8** [EddieYao8/FlashlightProject#6]
Electronic/software review 

Also, what hours besides the designated lab section is Chesterfield open for us?

Thanks,
Eddie

**Comment by mlp6** [comment]
Lab is open during all "normal" business hours and can be open other evenings if needed!

**Comment by mlp6** [comment]
Pseudo-code looking good... no promises something is missing, but quick inspection without compiling looks on track!  Schematic looks good too.  CAD time!
