### ISSUE TITLE
Milestone 04 Review

### ISSUE THREAD

**Issue by EddieYao8** [EddieYao8/FlashlightProject#7]
I'm not sure if I filled in my PCB board correctly.  

Also, can I use a connector for the LED so I could have more flexibility for the mechanical design?

**Comment by sphaerobolus** [comment]
A1 is probably not an Arduino, but an ATTiny, right? If it's an ATTiny, you'll want a different footprint. That 2x4 header you're using will be an exercise in frustration. 

We don't have the voltage regulators in the footprint you've used. We have them in TO-92 and TO-220. It would be difficult to kludge one of ours on your footprint. 

Be sure your traces are 12mil, at least. 20mil would be better. 

Increase your clearance so the groundplane doesn't extend between the pads of the SMT devices. That's a little tight if we photo-etch in house. 

I see a few vias on traces somewhat randomly. I presume these are testpoints?

**Comment by EddieYao8** [comment]
Thanks for the help.  I think I fixed the issues.  

The vias are the test point. 

I reuploaded the PCB. Could you check if I made the right changes?

**Comment by sphaerobolus** [comment]
looks good now!
